# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_macos:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Build & Test macOS
      run: xcodebuild test -project EssentialApp/EssentialApp.xcodeproj -scheme "CI_macos" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
  build_ios:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
    
    - name: Build & Test iOS
      run: xcodebuild clean build test -project EssentialApp/EssentialApp.xcodeproj -scheme "CI_ios" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" ONLY_ACTIVE_ARCH=YES
